@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

###
# @name create_user
POST {{baseUrl}}/account
Content-Type: application/json

{
    "name": "Daniel",
    "email": "fernandes@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "fernandes@gmail.com",
    "password": "123456"
}

###

# @name create_task

POST {{baseUrl}}/task
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Almoçar ao meio dia",
    "description": "Arroz, feijão, frango e legumes."
}

###

# @name fetch_tasks

GET {{baseUrl}}/task?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_task

DELETE  {{baseUrl}}/task/ae959535-83fa-4020-b09d-13393191a2db
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_task

PUT  {{baseUrl}}/task/4beb8050-b268-493e-ac64-81961e6d9465
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Novo nome",
    "description": "Descrição nova"
}

###

# @name view_task_details

GET {{baseUrl}}/task/4beb8050-b268-493e-ac64-81961e6d9465
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name mark_task_completed

PATCH {{baseUrl}}/task/4beb8050-b268-493e-ac64-81961e6d9465
Content-Type: application/json
Authorization: Bearer {{authToken}}
